### ISSUE TITLE
Cant install.

### ISSUE THREAD

**Issue by sunilgoudar** [abhishek72850/avas#2]
![Capture](https://user-images.githubusercontent.com/60724779/119518824-82139e80-bd96-11eb-9d7e-2222bd2bbce4.JPG)

**Comment by abhishek72850** [comment]
Are you using Termux? if yes then which version?

**Comment by sunilgoudar** [comment]
Termux 101
Latest from Playstore.

**Comment by abhishek72850** [comment]
Ok, try `apt upgrade` then try this command again

**Comment by sunilgoudar** [comment]
Hi bro,. Now i  did the setup of install.sh. But still getting some error. can please help me to do the complete setup?

**Comment by abhishek72850** [comment]
Of course join here https://t.me/avas_channel, so that i can reply faster

**Comment by abhishek72850** [comment]
try now: 
1. cd to the path where u have cloned the repo
2. run command `bash install.sh`

**Comment by sunilgoudar** [comment]
> Of course join here https://t.me/avas_channel, so that i can reply faster

I joined this group. but no option to discuss.

**Comment by sunilgoudar** [comment]
> try now:
> 
> 1. cd to the path where u have cloned the repo
> 2. run command `bash install.sh`

install.sh poping up many errors. im not able to solve.
![Capture](https://user-images.githubusercontent.com/60724779/119673570-15ada380-be59-11eb-8491-908987b7ef2d.JPG)

**Comment by abhishek72850** [comment]
Ok this seems to be the problem with lxml, can u install the latest version of termux from here: https://f-droid.org/repo/com.termux_113.apk they have discontinued the support for play store version.

**Comment by sunilgoudar** [comment]
> Ok this seems to be the problem with lxml, can u install the latest version of termux from here: https://f-droid.org/repo/com.termux_113.apk they have discontinued the support for play store version.

Ok bro.

**Comment by sunilgoudar** [comment]
Thanks for helping in Telegram to setup. Good Luck for your Future development.
